model:
  target: foley2025.temporal.alignment_learning.TemporalAlignmentLearning
  params:
    encoder_config:
      target: foley2025.data.greatest_hits.GreatestHitEmbeddingSequence
      params:
        video_encoder_config:
          #target: foley2025.data.greatest_hits.DummyTensors
          #params: {}
          target: 'foley2025.contrastive.encoder.ContrastiveSingleModality'
          checkpoint: 'checkpoints/video_encoder_finetuned.ckpt'

        audio_encoder_config:
          #target: foley2025.data.greatest_hits.DummyTensors
          #params: {}
          target: 'foley2025.contrastive.encoder.ContrastiveSingleModality'
          checkpoint: 'checkpoints/audio_encoder_finetuned.ckpt'

        encoder_batch_size: 16
        segment_duration_frames: 8
        embedding_save_dir: '/local/s2014203/embedding_sequences_v1'
        #embedding_save_dir: '/local/s2014203/embedding_sequences_zerotensors_L30'
        min_shift: 5
        max_shift: 15
        min_sequence_length: 30
        max_sequence_length: 30

    audio_tcc_model_config:
      target: foley2025.temporal.alignment_model.TransformerAlignmentModel
      params:
        input_size: 768
        output_size: 768
        n_layers: 4
        sequence_length: 30
        num_heads: 8
        dropout: 0.2

    tcc_loss_config:
      target: foley2025.temporal.loss.TCCLoss
      params:
        tcc_lambda: 0.05
        softmax_temperature: 0.1
        similarity_fn: 'negative-euclidean'
#      target: foley2025.temporal.loss.GTCCLoss
#      params:
#        similarity_fn: 'negative-euclidean'
#        n_components: 10
#        lbfgs_max_iters: 50
#        lbfgs_lr: 0.5
#        tcc_lambda: 0.05
#        window_ratio: 0.25
#        softmax_temperature: 0.1
#        gmm_min_variance: 0.5
#        divide_by_variance: False
#      target: foley2025.temporal.legacy_loss.GTCCLoss
#      params:
#        n_components: 10
#        lbfgs_max_iters: 50
#        window_ratio: 0.25
#        softmax_temperature: 0.1
#        max_gmm_iters: 1
#        tcc_lambda: 0.05
#          target: foley2025.temporal.legacy_loss.TCCLoss
#          params:
#            tcc_lambda: 0.05
#            softmax_temperature: 0.1
    tcc_loss_weight: 0.1

    alignment_loss_config:
      target: torch.nn.MSELoss
      params: {}
    alignment_loss_weight: 10


    alignment_procedure_config:
      target: foley2025.temporal.alignment_procedure.AlignFunction
      params:
        softmax_temperature: 0.1
        conf_similarity_str: 'cosine'

    optim_learn_rate: 1e-6
    #optim_weight_decay: 1e-9
    optim_weight_decay: 0.0

data:
  target: foley2025.data.greatest_hits.GreatestHitFullClipsDataModule
  params:
    batch_size: 32
    num_workers: 4
    shuffle_every_epoch: True
    splits_path: data
    data_path: '/local/s2014203/vis-data'

wandb:
  name: "Temporal_Retrainedv1"
  notes: "Temporal alignment network, now changed to have only an audio network."

